                              			
				<div class="content-module">
				
					<div class="content-module-heading cf">
					
						<h3 class="fl"><?php echo $this->translate('Dodaj ofertę') ?></h3>
						<span class="fr expand-collapse-text"><?php echo $this->translate('Schowaj') ?></span>
						<span class="fr expand-collapse-text initial-expand"><?php echo $this->translate('Wysuń') ?></span>
					
					</div> <!-- end content-module-heading -->
					
					
					<div class="content-module-main">
                                            <h2 class="title">Krok 2/4</h2>
                                            <h3>Wypełnij formularz</h3>
                                            
                                            <?php
                                               
                                            ?>
					
					</div> <!-- end content-module-main -->
				
				</div> <!-- end content-module -->
				
			

			